name: Dependabot to Gerrit
on:
  push:

jobs:
  open-or-update-change:
    runs-on: ubuntu-latest
    #if: github.actor == 'dependabot[bot]'
    steps:
      - name: Checkout HEAD commit
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          # Depth of 3 at least, so we have the needed commit, a clean parent commit, and the rest of the code in a third
          fetch-depth: 10
      - name: Run dependabot gerrit action
        uses: wmde/dependabot-gerrit-action@main
        with:
          password: ${{ secrets.DEPENDABOT_GERRIT_PASSWORD }}
          dry_run: true
          user: Addbot
          email: addshorewiki+addbot-dependabot@gmail.com
